name: Trial

on:
  push:
    branches: ["trial"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: npm ci
      - run: npm run dev
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
